### ISSUE TITLE
Erro no JS do Checkout

### ISSUE THREAD

**Issue by agranado2k** [iugu/iugu-woocommerce#14]
Algum problema está ocorrendo com js do plugin na página de Checkout. Recebo tanto uma mensagem na aba do console, quanto um aviso de retorno para o usuário sobre o problema, como na figura abaixo.

![bug_plugin_iugu](https://cloud.githubusercontent.com/assets/838518/8755822/20902202-2ca4-11e5-8f3b-756ad3ec8d4f.jpg)

As configurações que estou usando são:
* WP 4.2.2
* Woo 2.3.13 
* Plugin Iugu 1.0.6
* [Tema Aurum 2.4.1] ( http://themeforest.net/item/aurum-minimalist-shopping-theme/9600822 )

Alguém saberia o que pode ser?

Abraços e obrigado galera!

**Comment by claudiosmweb** [comment]
Problema é o primeiro erro `Uncaught SyntaxError`.
Corrija ele que o plugin vai funcionar.

**Comment by agranado2k** [comment]
Olá @claudiosmweb, o problema é como corrigir esse erro? Ele acontece apenas quando instalo o plugin do Iugu.. :/

Alguma ideia do que possa ser?

**Comment by claudiosmweb** [comment]
@agranado2k o primeiro erro ai não tem nada relacionado com o Iugu.js.
Você me perguntar como arrumar o seu site foge de qualquer tipo de escopo do funcionamento deste plugin, você não acha?
