### ISSUE TITLE
Checkout - Payment

### ISSUE THREAD

**Issue by lucasvieira20** [iugu/iugu-woocommerce#17]
Após inserir os dados da minha compra e informações adicionais, não consigo passar para finalização de pagamento.

**Comment by claudiosmweb** [comment]
O que acontece? Não consegue porque?

**Comment by lucasvieira20** [comment]
Estava funcionando normalmente o meio de pagamento através do IUGU Woocommerce porém parou de funcionar e está dando a seguinte mensagem:

Cartão de crédito: Por favor, tenha certeza que os dados do seu cartão foram inseridos corretamente e que o seu navegador suporta JavaScript.

Antes no momento do cadastro do cartão ele conseguia separar a numeração, colocar máscara na data, porém junto a esse erro começou a não fazer mais.

Toda ajuda será bem vinda.

**Comment by claudiosmweb** [comment]
> Antes no momento do cadastro do cartão ele conseguia separar a numeração, colocar máscara na data, porém junto a esse erro começou a não fazer mais.

Então tem erro de JavaScript na sua página e esta quebrando este plugin.
Corrija todos os erros que aparecerem no console do seu navegador e vai tudo voltar e funcionar como antes.

**Comment by lucasvieira20** [comment]
Obrigado pela atenção Claudio, 

Vou analisar os erros do console.
