### ISSUE TITLE
Erro ao finalizar a compra. Por favor tente novamente

### ISSUE THREAD

**Issue by mesquitanderson** [iugu/iugu-woocommerce#18]
O meu checkout estava até com problema, porém provocado pelo meu tema AVADA que foi corrigido com uma nova versão do jQuery. 

Após isso voltou a funcionar o pagamento com cartão de crédito normalmente, após alguns pagamento me reportou a seguinte mensagem:

Erro ao finalizar a compra. Por favor tente novamente

Lembrando que estou utilizando a API Token de Testes e no meu painel do IUGU também está direcionado para testes.

**Comment by mmattei** [comment]
Para contribuir...

Estou utilizando o ótimo plugin do Claudio com Iugu em sandbox, tudo funcionando perfeitamente e sempre de primeira. Hoje após a instalação do "WooCommerce Subscriptions" as compras com assinatura começaram a dar _"Erro ao finalizar a compra. Por favor tente novamente_". Mesmo com o erro o pedido chega no Iugu mas com status "Pendente". Testando produtos que não tem esquema de assinatura, o erro não ocorre. No log do plugin não vejo nada de errado:

______________________________________________________
06-05-2016 @ 16:30:21 - Doing charge for order 4448...
06-05-2016 @ 16:30:21 - Creating an invoice on Iugu for order 4448 with the following data: Array
(
    [email] => XXXXXXXX
    [due_date] => 06-06-2016
    [return_url] => http://XXXXXXXX/finalizar-compra/order-received/4448?key=wc_order_57547dcd12b14
    [expired_url] => http://XXXXXXXX/carrinho/?cancel_order=true&amp;order=wc_order_57547dcd12b14&amp;order_id=4448&amp;redirect&amp;_wpnonce=94254c25f0
    [notification_url] => http://XXXXXXXX/wc-api/WC_Iugu_Credit_Card_Gateway/
    [ignore_due_email] => 1
    [payable_with] => credit_card
    [custom_variables] => Array
        (
            [0] => Array
                (
                    [name] => order_id
                    [value] => 4448
                )

        )

    [items] => Array
        (
            [0] => Array
                (
                    [description] => Plano Loja Lite
                    [price_cents] => 219083
                    [quantity] => 1
                )

            [1] => Array
                (
                    [description] => Impostos
                    [price_cents] => 19717
                    [quantity] => 1
                )

        )

)

06-05-2016 @ 16:30:23 - Invoice created successfully!
______________________________________________________

- Todas versões atualizadas
- Plugins instalados conforme manuais
- APIs/Tokens ok
- Sandbox nas duas pontas
- fsockopen/cURL, etc, ok

Como o WooCommerce Subscriptions aguarda as informações para mudar de status, pode ser que alguma "conversa" tenha sido interrompida com sua inclusão no produto.

Valeu!

**Comment by mmattei** [comment]
Nova atualização:

No meu caso o problema era na conta do Iugu que por padrão tem uma limitação de valores para transações via cartão, nesse caso eram os R$1000,00. Essa limitação tem relação com controle anti fraude e chargerback.

Gostaria de deixar meus agradecimentos e parabéns ao Claudio pelo ótimo trabalho.

Abs!

**Comment by mesquitanderson** [comment]
Boa noite mmattei e como foi que você realizou essa alteração? Desde já muito obrigado. 

Grande abs.

**Comment by mmattei** [comment]
Fala Anderson!

Essa configuração é feita quando vc sobe a documentação no Iugu. Se tu já
subiu, tem que abrir um chamado com eles (pode ser via chat) e pedir o
aumento do limite. Tem que ser aprovado por eles por conta das questões de
fraude.

Infelizmente não temos acesso direto para configurar via dashboard da
conta....

O duro foi ter perdido umas quatro horas entre plugins e woocommerce...

Qualquer coisa escreve ae, estou com chamado aberto lá...

Abs

Em segunda-feira, 6 de junho de 2016, mesquitanderson <
notifications@github.com> escreveu:

> Boa noite mmattei e como foi que você realizou essa alteração? Desde já
> muito obrigado.
>
> Grande abs.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/iugu/iugu-woocommerce/issues/18#issuecomment-224100649>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS2WU7M1VDSO6R30Ln9oAl5LIKh9DRkEks5qJJcdgaJpZM4IjJef>
> .
>


-- 
Marcus Mattei
Enviado via iPhone

**Comment by claudiosmweb** [comment]
Que bom que esta tudo certo então com o plugin. Fechando aqui.

**Comment by dvdcoelho** [comment]
Ola... tambem estou com esse erro, [Erro ao finalizar a compra. Por favor tente novamente], no meu caso uso mercado pago e o plugin do pix por pig mas nada funciona, antes funcionava pagamento apos recebimento mas agora nada meu link opaganhei.online se puderem me ajudem .
