### ISSUE TITLE
Emails de notificação

### ISSUE THREAD

**Issue by casareumbarato** [iugu/iugu-woocommerce#19]
Olá,

antes de mais nada parabéns pelo plugin, fica tudo perfeito!

Meu único problema foi o seguinte: utilizando outros gateways de pagamento em meu woocommerce (ex: paypal) todos os e-mails de notificação (pedido recebido, pagamento processado, etc) foram enviados normalmente pela loja (tanto para o cliente quanto para o vendedor).

Entretanto ao habilitar o Iugu (apenas ele, desativando os demais) os e-mails param de ser enviados.

Desativei novamente o iugu e reativei o paypal… e os e-mails voltaram a funcionar.

Vocês saberiam me dizer o que pode estar ocorrendo?

PS: utilizo Woocommerce com Dokan.

Muito obrigada!

**Comment by claudiosanches** [comment]
Isso não tem ligação com os outros plugins, geralmente isso acontece quando os status dos pedidos não estão sendo alterados e por isso que nenhum e-mail é enviado.
O status vai ser alterado se o seu servidor for capaz de receber as notificações de mudança de status do Iugu, tem que verificar se tem algum firewall, ModSecurity ou algo bloqueando isso.

**Comment by casareumbarato** [comment]
Oi, tudo bom com você?

Obrigada pelo seu contato

Parece mentira mas não é: estamos de férias!

O ano foi duro, muito trabalho, muita criatividade colocada em prática pra tentar driblar as difíceis situações... merecemos descansar um pouquinho, né? :)

Então... do dia 24/12 a 08/01 estarei ausente descansando um pouco.

Durante este tempo, a Marry (que faz parte da nossa equipe) estará responsável por verificar nossos e-mails. Se for algo de trabalho, não se preocupe que ela responderá em horário comercial, ok?

O contato direto dela é marry.casareumbarato@gmail.com

Desejamos um 2017 incrível pra você (e pra todos nós!).

Beijos grandes, nos falamos em breve!

Mariana & Equipe do Casar é um Barato

**Comment by casareumbarato** [comment]
Olá Claudio, obrigada pelo seu retorno!

No meu caso, o status do pedido foi alterado. Ou seja: a conclusão da venda com sucesso via Iugu aparece perfeitamente no sistema - o que me faz crer que o sistema está sendo notificado.

Só não consegui descobrir o motivo pelo qual os e-mails não são disparados quando o pagamento é feito via Iugu.

Isso nunca ocorreu com ninguém antes?
