### ISSUE TITLE
Erro no boleto bancário

### ISSUE THREAD

**Issue by xguiboy** [iugu/iugu-woocommerce#25]
O plugin está com um erro ao finalizar a compra para clientes que moram em cidades que possuem CEPs únicos. ex 88500-000

**Comment by igorbayma** [comment]
(Resolvido lá pelo grupo do woocommerce do facebook) 
Pessoal, resolvido com a ajuda do Éliton Torri no nome da variável, segue:
Abra o arquivo
/includes/class-wc-iugu-api.php
Vai até a linha
'state' => $order->billing_state,
E coloca abaixo
"district" => $order->billing_neighborhood,

Salva e boas vendas

**Comment by xguiboy** [comment]
Muito obrigado @igorbayma fiz a alteração e os testes tudo funcionando lindamente.
