### ISSUE TITLE
Pedidos falsos

### ISSUE THREAD

**Issue by xguiboy** [iugu/iugu-woocommerce#33]
Bom dia, estou tento um problema em meu site que é muitos pedidos falsos, já coloquei recaptcha, anti-spam e nada acabou com o problema, quando vou no iugu vejo que o usuário realizou várias tentativas de pagamento pelo cartão de crédito usando vários cartões diferentes, gostaria de saber se é possível limitar o máximo de tentativas de pagamento para o cartão para por exemplo 3, depois bloquear o ip do usuário ou algo do tipo e podendo ser desbloqueado por mim caso necessário.

**Comment by andsnleo** [comment]
oi, @xguiboy!

tô fechando a issue porque, [como respondido no fórum do plugin lá no Wordpress](https://wordpress.org/support/topic/pedidos-falsos-cartao-de-credito/), entendemos que essa não é uma responsabilidade do nosso plugin de gateway de pagamento. uma solução de anti-fraude é recomendada.

inclusive, uma coisa que não tinha adicionado lá: o WooCommerce tem um plugin de anti-fraude, o que pode facilitar a integração com a sua loja: https://docs.woocommerce.com/document/woocommerce-anti-fraud/ :smiley: 

abraço!
