### ISSUE TITLE
Tradução pt_BR não funciona

### ISSUE THREAD

**Issue by jsvini** [iugu/iugu-woocommerce#38]
Em uma instalação limpa o idioma do plugin fica sempre em inglês, tanto no painel quanto nos forms do checkout. 

Wordpress 4.9.6–pt_BR
Woocommerce 3.3.5
WooCommerce iugu 2.0.2

![image](https://user-images.githubusercontent.com/4185886/40324504-1255894a-5d0f-11e8-965d-1eb0ec3e136f.png)

**Comment by andsnleo** [comment]
@jsvini desculpa a demora. por algum motivo, o Wordpress considera uma tradução antiga que fica na camada do sistema, em vez de pegar a da versão mais atualizada do plugin. para resolver isso:

1) instalar o plugin Loco Translate
2) acessar as traduções de plugins do Loco Translate
3) deletar a tradução no nível _Sistema_, e deixar a de _Autor_

qualquer coisa, me avisa, que providencio umas screenshots :)

**Comment by andsnleo** [comment]
@jsvini, deu certo? tô fechando a issue por inatividade. qualquer coisa, me avisa
