### ISSUE TITLE
Recorrência Iugu com WooCommerce Subscriptions

### ISSUE THREAD

**Issue by lucasdkp** [iugu/iugu-woocommerce#45]
Olá, gostaria de saber se a integração com o Woocommerce para assinaturas através do WooCommerce Subscriptions, o pagamento entra como recorrência ou avulso dentro da plataforma da Iugu?

**Comment by andsnleo** [comment]
oi, @lucasdkp! na iugu vai constar como pagamento avulso. o gerenciamento, no caso, fica dentro do woocommerce. mas estamos estudando a possibilidade de se refletir dentro do nosso sistema também :)
