### ISSUE TITLE
Recorrencia com subscriptions não passa em live, sandbox ok

### ISSUE THREAD

**Issue by edigomes** [iugu/iugu-woocommerce#54]
Bom dia,

A transação retorna: **Cartão de Crédito: Certifique-se de que suas informações de cartão de crédito estão corretas e seu navegador suporta JavaScript.**

```
No log eu tenho: 04-27-2019 @ 00:20:19 - Creating customer payment method for order 382...
04-27-2019 @ 00:20:19 - Error doing the charge for order 382: Missing the "iugu_token" and "customer_payment_method_id".
```

Este erro só ocorre em live, na sandbox funciona 100%.

**Comment by edigomes** [comment]
RESOLVIDO

Se a conta que você está usando para fazer a compra foi criada quando o plugin estava configurado com um ID de testes, essa mesma conta não vai passar a compra no modo LIVE.

**Comment by MonneratRJ** [comment]
Eu criei uma conta no modo LIVE e ainda assim o problema Missing the "iugu_token" and "customer_payment_method_id". persiste... começou após eu fazer uma migração entre 2 servidores... falaram q talvez fosse o adblocker mas eu já desativei, tentei aba anônima e até num pc que sequer tem adblocker e o problema persiste, no entanto o boleto bancário funciona.

**Comment by ferdz-vollup** [comment]
Estou com o mesmo problema? Encontraram uma solução ?

**Comment by MonneratRJ** [comment]
> Estou com o mesmo problema? Encontraram uma solução ?

Estou até agora com meus clientes sem poder usar o cartão de crédito por causa disso... ainda não deram nenhuma solução

**Comment by ferdz-vollup** [comment]
@MonneratRJ está usando a YUGU e o plugin de assinaturas do Woocommerce ?

**Comment by MonneratRJ** [comment]
Não, eu estou usando o plugin da própria iugu voltada pro woocommerce...

**Comment by ferdz-vollup** [comment]
O cartão funciona nas compras avulsas, só tem erro quando é recorrência
(assinatura).

[image: imagem vollup] <https://www.vollup.com/campanhas>
[image: dados] <fernando@vollup.com> [image: espaço vazio]
[image: logo vollup]
<http://www.vollup.com/?utm_source=assinatura&utm_medium=email&utm_campaign=2020>
[image:
logo instagram] <https://www.instagram.com/vollup/> [image: logo linkedin]
<https://www.linkedin.com/company/vollup/> [image: logo facebook]
<https://www.facebook.com/vollup>
[image: divisoria]

*VOLLUP.COM <http://VOLLUP.COM> © Desde 2012.* Esta mensagem pode conter
informação confidencial ou privilegiada, sendo seu sigilo protegido por
lei. Se você não for o destinatário ou a pessoa autorizada a receber esta
mensagem, não pode usar, copiar ou divulgar as informações nela contidas ou
tomar qualquer ação baseada nessas informações. Se você recebeu esta
mensagem por engano, por favor, avise imediatamente ao remetente,
respondendo o e-mail e em seguida apague-a. Agradecemos sua cooperação.
Antes de imprimir esse documento, pense no meio ambiente.


Em seg., 28 de set. de 2020 às 16:36, Marcelo Monnerat Castello <
notifications@github.com> escreveu:

**Comment by MonneratRJ** [comment]
É no meu caso nenhuma compra por cartão está funcionando.

**Comment by ferdz-vollup** [comment]
Tudo leva a crer que o problema é com a IUGU e não com o Woocommerce !

[image: imagem vollup] <https://www.vollup.com/campanhas>
[image: dados] <fernando@vollup.com> [image: espaço vazio]
[image: logo vollup]
<http://www.vollup.com/?utm_source=assinatura&utm_medium=email&utm_campaign=2020>
[image:
logo instagram] <https://www.instagram.com/vollup/> [image: logo linkedin]
<https://www.linkedin.com/company/vollup/> [image: logo facebook]
<https://www.facebook.com/vollup>
[image: divisoria]

*VOLLUP.COM <http://VOLLUP.COM> © Desde 2012.* Esta mensagem pode conter
informação confidencial ou privilegiada, sendo seu sigilo protegido por
lei. Se você não for o destinatário ou a pessoa autorizada a receber esta
mensagem, não pode usar, copiar ou divulgar as informações nela contidas ou
tomar qualquer ação baseada nessas informações. Se você recebeu esta
mensagem por engano, por favor, avise imediatamente ao remetente,
respondendo o e-mail e em seguida apague-a. Agradecemos sua cooperação.
Antes de imprimir esse documento, pense no meio ambiente.


Em seg., 28 de set. de 2020 às 16:56, Marcelo Monnerat Castello <
notifications@github.com> escreveu:

**Comment by MonneratRJ** [comment]
Exatamente, pq até o boleto da IUGU funciona, mas o cartão parou de funcionar... mas a IUGU não conseguiu consertar e já faz quase 1 mês!

**Comment by ferdz-vollup** [comment]
@MonneratRJ entre em WooCommerce > Status > Log.. selecione o log da IUGU e clique em visualizar !

**Comment by MonneratRJ** [comment]
@ferdz-vollup eu criei até um pastebin pra eles, é o mesmo erro desde sei lá, dia 8/09 e nada de resposta...
https://pastebin.com/Y3tpaMeJ

**Comment by upsitesdigital** [comment]
Para resolver o problema é precisar fazer rollback no plugin e utilizar a versão 2.1.6 que você pode baixar no final desta página https://wordpress.org/plugins/iugu-woocommerce/advanced/

**Comment by JoaoRuani** [comment]
Mesmo problema, no boleto funciona mas no cartão não. 
Versão do plugin 2.2.1

**Comment by felipepitol** [comment]
Estou tendo o mesmo problema:
`Cartão de crédito: Certifique-se de que suas informações de cartão de crédito estão corretas e seu navegador suporta JavaScript.`

- Ja fiz downgrade de versões;
- Ja instalei versão mais atualizada;
- Ja verifiquei o versões diferentes do plugin subscription;
- Ja limpei cache de navegador, CDN, etc;
- Ja tentei contato com o suporte (_Via telefone ele dizem para abrir um chamado, porem o site deles pede para logar na conta, e mesmo logando na conta, acusa estar deslogado_);

Alguém tem ideia de qual caminho seguir? Alguem conseguiu resolver?
