### ISSUE TITLE
Status processando mesmo com pagamento inexistente

### ISSUE THREAD

**Issue by luigibonafe** [iugu/iugu-woocommerce#55]
Estou usando LearnDash + WooCommerce + Iugu e enfrento um problema sério: qualquer pedido via boleto ou cartão de crédito está sendo marcado com o status "processando" ou "concluído" no WooCommerce, independente de o pagamento ter sido feito. Fiz diversos testes e, no painel de controle da iugu, todos os pedidos estão pendentes aguardando pagamento. Mas todos eles aparecem como pagos no WooCommerce. Isso só não está acontecendo quando habilito outro meio de pagamento, como transferência bancária direta. Esse é o único caso em que o WooCommerce sinaliza o status "Aguardando".
Alguém já enfrentou problema parecido e tem alguma pista de onde pode estar o problema?
Obrigado desde já

**Comment by TiagoRodrigues** [comment]
resolveu amigo?

**Comment by emernuness** [comment]
> Estou usando LearnDash + WooCommerce + Iugu e enfrento um problema sério: qualquer pedido via boleto ou cartão de crédito está sendo marcado com o status "processando" ou "concluído" no WooCommerce, independente de o pagamento ter sido feito. Fiz diversos testes e, no painel de controle da iugu, todos os pedidos estão pendentes aguardando pagamento. Mas todos eles aparecem como pagos no WooCommerce. Isso só não está acontecendo quando habilito outro meio de pagamento, como transferência bancária direta. Esse é o único caso em que o WooCommerce sinaliza o status "Aguardando". Alguém já enfrentou problema parecido e tem alguma pista de onde pode estar o problema? Obrigado desde já

Olá @luigibonafe estou com o mesmo problema conseguiu resolver?
