### ISSUE TITLE
Manter arquivo .editorconfig

### ISSUE THREAD

**Issue by claudiosmweb** [iugu/iugu-woocommerce#6]
Manter o arquivo `.editorconfig` removido em https://github.com/iugu/iugu-woocommerce/commit/98b90e8bab612c5ede2cfe1cae3dd3257f27ffb9

Este arquivo é importante para todo mundo que for contribuir com o plugin manter uma certa consistência em é escrito como é arquivos.

Aqui página do .editorconfig explicando o projeto e mostrando os apps e plugins para baixar para cada IDE/editor http://editorconfig.org/

**Comment by braising** [comment]
Ok, obrigado pela consideração, vou recolocar o arquivo

**Comment by claudiosmweb** [comment]
Tranquilo, estou trabalhando em umas correções agora.
